### ISSUE TITLE
Integrate into VVVV.Audio?

### ISSUE THREAD

**Issue by tebjan** [microdee/mp.vaudio#1]
would love to see them nodes in the repo in one place... why don't make PR with the content then this repo can be closed?

**Comment by microdee** [comment]
I'm alright with them being extensions. also it has couple of dependencies
which you might not want to be attached to vvvv.audio itself. like fft
based modules use nodes from mp.essentials and midi behaviour nodes are
using messages and VObjects.

**Comment by tebjan** [comment]
ah, makes sense with the dependencies... nice nodes though.
